---
partners:
  - identifier: tulpa_info
    name: Tulpa.info
    title: The main international resource about the phenomenon
    url: https://tulpa.info/
  - identifier: deskchan
    name: DeskChan
    title: Personal digital assistant with character customization
    url: https://deskchan.info/
