---
image:
  name: klakegg/hugo:ext-alpine
  entrypoint: ['']

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk add --update --no-cache git
  - git submodule update --init --recursive

stages:
  - build
  - test
  - deploy

test:
  stage: test
  script: hugo --renderToMemory
  except:
    - master

pages:
  stage: deploy
  script: hugo --gc --minify
  artifacts:
    paths:
      - public
  only:
    - master
