---
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  stage: test
  script: hugo --renderToMemory
  except:
    - master

pages:
  stage: deploy
  script: hugo -e production
  artifacts:
    paths:
      - public
  only:
    - master
