---
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk update
  - apk upgrade
  - apk add git

test:
  stage: test
  script: hugo --renderToMemory
  except:
    - master

pages:
  stage: deploy
  script: hugo --minify
  artifacts:
    paths:
      - public
  only:
    - master
